# Generated by Django 6.0.3 on 2026-03-04 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('notes', 'Notes'), ('pyq', 'PYQ'), ('textbook', 'Textbook')], max_length=50)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField()),
                ('scheme', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('scheme', 'dept', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('credit', models.IntegerField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.curriculum')),
            ],
        ),
    ]
