# Generated by Django 6.0.3 on 2026-03-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSoftwareNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('drive_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_software_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSoftwarePyq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_year', models.IntegerField(blank=True, null=True)),
                ('exam_month', models.TextField(blank=True, null=True)),
                ('drive_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_software_pyq',
                'managed': False,
            },
        ),
    ]
